package br.com.coregate.domain.enums;

public enum TransactionType {
    TRANSACTION_TYPE_UNSPECIFIED,
    TRANSACTION_TYPE_PURCHASE,
    TRANSACTION_TYPE_REVERSAL,
    TRANSACTION_TYPE_REFUND,
    TRANSACTION_TYPE_BALANCE_INQUIRY,
    TRANSACTION_TYPE_WITHDRAWAL,
    TRANSACTION_TYPE_AUTHORIZATION,
    UNRECOGNIZED}